# Generated by Django 5.1.15 on 2026-09-21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FogQuota",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("work_date", models.DateField()),
                ("max_hours", models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("used_minutes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("zone", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fog_quotas", to="core.zone")),
            ],
            options={
                "ordering": ["-work_date", "zone_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="fogquota",
            constraint=models.UniqueConstraint(fields=("zone", "work_date"), name="uniq_fog_quota_zone_date"),
        ),
    ]
